import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

SENDER_EMAIL = "sathya.s.ihub@snsgroups.com"
SENDER_PASSWORD = "nakb gete imyy ytlp"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

def send_quiz_email(recipient_email, quiz_link):
    subject = "🧪 Your AI-Generated Quiz Link"
    body = f"""
Hi there!

Here is your personalized quiz link generated by the AI Lesson Planner:
{quiz_link}

Good luck!
"""

    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = recipient_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())
        server.quit()
        print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Email sending failed: {e}")
